### ISSUE TITLE
Calendar: console.log in minfied file breaks in Internet Explorer

### ISSUE THREAD

**Issue by nahojd** [mozbrick/brick#106]
In Internet Explorer, there is no console object until you open the dev tools (see http://stackoverflow.com/questions/3326650/console-is-undefined-error-for-internet-explorer). 

Unfortunately, even the minified version of the calendar component contains a few console.log calls, which for example breaks the "next month"-arrow (at least in IE9). These should be removed or at least check if console is defined first.

This is the line that breaks next month in IE9: https://github.com/mozilla/brick/blob/master/dist/x-tag-calendar.js#L209
The console.log seems rather unnecessary anyway...

**Comment by fwenzel** [comment]
Yeah that smells like leftover from development.

**Comment by JoshStrobl** [comment]
So, we can do one of two things:
1. Check if console is defined first prior to doing console.\* commands
2. Remove console.\* calls from the Javascript.

Personally, I'd go with the first one, however it **may** add some minor overhead since every time we call console.log, console.warn, etc. we'll be checking if it is defined or not (which will fix the IE issue).

If we remove console.\* commands, that **could** make it more difficult for devs to debug their apps, so we should really figure out a balancing point.

Also should be noticed that console.\* commands are in the following files:

```
x-tag-tooltip.js
x-tag-deck.js
brick.js
x-tag-core.js
x-tag-calendar.js
```

If you are on Linux and have ack-grep installed, you can see for yourself (obviously ignore the *.min.js files) by doing the following command in the dist folder:

```
ack -l -H --type=js -r 'console'
```

Either way, I'd happily write the patch and submit a pull request!

**Comment by potch** [comment]
Hey @JoshStrobl! I'd be happy if the console.log calls were removed (just was well to be a good citizen in a production environment). I'm off right now, but would happily accept a pull request! Thanks :)

**Comment by JoshStrobl** [comment]
@potch Awesome, I'll go ahead and patch it when I wake up in the morning! I'll also minify the fixed files as well, so the minified JS files will be patched as well!

**Comment by potch** [comment]
Thanks! Don't worry about the minification, I'm going to spin a new build
once I merge.

**Comment by callahad** [comment]
I think this has been resolved. As of 4a8f97617839cab858c0e49caf6443b5b6c6671a, the only live calls to `console.log` are hidden behind a `logFlags.dom` check:

```
% grep console.log dist/*[^(min)].js
dist/brick.js:                    logFlags.dom && console.log("inserted:", element.localName);
dist/brick.js:            logFlags.dom && console.log("watching shadow-root for: ", node.localName);
dist/x-tag-core.js:   *              console.log("a fancy-button was created",
dist/x-tag-core.js:  //console.log('inserted: ', element.localName);
dist/x-tag-core.js:        logFlags.dom && console.log('inserted:', element.localName);
dist/x-tag-core.js:    logFlags.dom && console.log('watching shadow-root for: ', node.localName);
dist/x-tag-core.js:        //logFlags.dom && console.log(n.localName);
dist/x-tag-core.js:        //logFlags.dom && console.log(n.localName);
```

There are a few calls to `console.warn` that bypass `logFlags.dom`, but all of those are instead guarded by conditional error checks.

**Comment by fwenzel** [comment]
@potch are we console.log free now?

**Comment by potch** [comment]
Brick components are now `console.log` free!
