### ISSUE TITLE
CSP Warnings in Validator

### ISSUE THREAD

**Issue by JasonWeathersby** [mozbrick/brick#121]
When running an App through the Marketplace Validator we get CSP Warnings.  Here is the first:
Warning: It appears that your code may be performing an action which violates the CSP (content security policy) for privileged apps.

You can find more information about what is and is not allowed by the CSP on the Mozilla Developers website. https://developer.mozilla.org/Apps/CSP
js/brick-0.10.0.js
459
460
461
if (definition.is) {
    var inst = document.createElement(definition.tag);
    nativePrototype = Object.getPrototypeOf(inst);
CSP Violation Detected

**Comment by potch** [comment]
A warning isn't a full violation, right? This looks like validator is worried we might createElement('script'). Unless I'm missing something.

**Comment by fwenzel** [comment]
oooh I think it's because the validator does static analysis so it can't know what's inside that variable at execution time. The actual CSP engine, of course, will know and will fail if this is a script (which it isn't).

I'd probably close this because this warning is legit, but so is Brick's code.

**Comment by potch** [comment]
@fwenzel That was my assumption as well. Gonna close this up.
