### ISSUE TITLE
BrickJS conflicting with Zepto JS

### ISSUE THREAD

**Issue by svapreddy** [mozbrick/brick#154]
I have a table content inside x-card of deck. I have registered tap event with table row using zepto touch events (Delegation). But when I actually see with break point, the same handler is being fired twice. Once by Zepto and next by BrickJS. Is there any solution for this?

**Comment by svapreddy** [comment]
`Thanks for no reply`. BrickJS has very severe issues in Android mobile. Sometimes does not let you even focus in textbox and does not let you click. I have removed the BrickJS and I am breathing freely now. And looking at MDN docs information every developer hope for Cross browser solution from Mozilla.

**Comment by sole** [comment]
Hey @svapreddy, sorry no one got back to you.

Thanks for filing this bug! We rely on people like you to make Brick better.

If you're still interested in getting help we'd appreciate if you could show us an example that demonstrates this issue so we can find out if it's an issue of Zepto, Brick or _both at the same time_.
Otherwise it's really hard to help :-)

Thanks and sorry for the delay!

**Comment by svapreddy** [comment]
@sole Hello Sole, The issue is in BrickJS fireEvent function where `dispatchEvent` will fire events like `tap`. The problem is while using it with Zepto or any other touch library in mobiles ( This is the use case as people need more events like swipe etc.. ). I have fixed the issue by adding a parameter to BrickJS event data as `isBrickTap` and checking the same at my event handler function with a condition to recognize whether an event is from BrickJS or any other library. This has fixed the issue, initially tried removing firing of `tap in fireEvent` but that caused textboxes getting no focus in Android and iOS. Hope this will help you people to improve BrickJS.
