### ISSUE TITLE
x-card should support a "src" attribute

### ISSUE THREAD

**Issue by cfjedimaster** [mozbrick/brick#165]
It would be cool if x-card could be sourced via XHR. So for example:

```
<x-deck>
    <x-card transition-type="slide-right" src="card1.html"></x-card>
    <x-card transition-type="slide-left" src="card2.html"></x-card>
    <x-card transition-type="fade-scale">2<span>I'm just inline.</span></x-card>
```

</x-deck>

**Comment by pennyfx** [comment]
We have a panel that does that.  

https://github.com/x-tag/panel

You can download it here.

http://x-tags.org/download

**Comment by cfjedimaster** [comment]
Would that work as a drop in replacement for x-card? That would be cool. :)

**Comment by pennyfx** [comment]
You'll have to nest them like so:

```
<x-card>
  <x-panel src="page1.html"></x-panel>
</x-card>
```

**Comment by cfjedimaster** [comment]
I'm speaking hypothetical now - but I wonder if x-deck could be updated to
allow _any_ block style tag.

On Wed, Apr 16, 2014 at 4:24 PM, Arron Schaar notifications@github.comwrote:

> You'll have to nest them like so:
> 
> <x-card>
>   <x-panel src="page1.html"></x-panel>
> </x-card>
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/brick/issues/165#issuecomment-40654226
> .

## 

# 

Raymond Camden, Web Developer for Adobe

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by pennyfx** [comment]
The cards have some special functionality, so it's not possible to use any block element.  
https://github.com/x-tag/deck/blob/master/src/deck.js#L143

However, hypothetically, you can create a new custom element that extends from x-card and add any special functionality you want.

For example:

```
xtag.register('x-super-card', {
  mixins: ['request'],
  extends: 'x-card'
});
```

In this sample, I'm using the same request mixin that is used in x-panel and extending from an x-card.     The request mixin is called `x-tag-mixin-request` in Bower.
http://x-tags.org/docs#custom-tag-registration-mixins

I reviewed our x-deck code and it looks like it is hard coded to look for `x-card` in a few places so that's not good.  I'll create a bug to improve the deck to make it more extensible, so this way of extending elements would work.

**Comment by potch** [comment]
The goal in Brick 2.0 will be to allow any element to be a 'card' in a deck and remove the need for a specific card element. Right now this is not yet the case, so leaving this bug open to track.

**Comment by dotch** [comment]
will be tracked in https://github.com/mozbrick/brick-deck/issues/6
