### ISSUE TITLE
Make?

### ISSUE THREAD

**Issue by sole** [mozbrick/brick#17]
Hey guys

Make?

In nodeland??

I thought Grunt was the commonly accepted solution to the building-phase-problem.

:-)

**Comment by tofumatt** [comment]
If you can do it without requiring more tools though, why not? Make is super easy and nearly every developer has it.
- tofumatt | http://tofumatt.com

**Comment by sole** [comment]
So my point was that... _web_ developers do _not_ use make. 

Most of them will at most install node.js + npm by downloading a precompiled package with the installer, then double click it, and follow the instructions.

I mean I don't use make either unless I'm in C/C++ land. Its syntax is confusing to people who don't know it already, it's something different from anything else, and generally why!?

But this was just an innocent, devil's advocate (or web developer's advocate) observation and don't want to "bikeshed" as Jen would put it :angel:

**Comment by pennyfx** [comment]
What about the Windows users?    /ducks

**Comment by ldoubleuz** [comment]
Cygwin? I have a link with instructions on how to get make with Cygwin in the docs. (It's how I set it up, at least.)

**Comment by fwenzel** [comment]
Gnu Make runs on windows right?

**Comment by pennyfx** [comment]
Yeah, I didn't know that existed.  But regardless, I think we should be moving towards Grunt for build tasks.
Having to push end users to install more software is not optimal.  Node/Npm and running `npm install` is already part of the process.  Simply include Grunt under `devDevpendencies`.  Then instead of running `make` as your next command, it becomes `grunt build` or even `grunt`.

**Comment by potch** [comment]
I explicitly didn't choose grunt in the short term because I wasn't interested in learning grunt when our main purpose was to ship code. Worth looking into, but not in the short term when make exists and works.

**Comment by potch** [comment]
remember @sole, **Java** is still a "commonly accepted solution" in some parts.

**Comment by wilmoore** [comment]
> What about the Windows users?

@pennyfx 
- [MSYS is a collection of GNU utilities such as bash, make, gawk and grep](http://www.mingw.org/node/18)
- [Make for Windows ](http://gnuwin32.sourceforge.net/packages/make.htm)
- [GNU utilities for Win32 -- includes make.exe](http://unxutils.sourceforge.net/)

> I thought Grunt was the commonly accepted solution to the building-phase-problem.

@sole It is picking up steam. As far as I've seen, most of the packages in `npm` (as you say, **nodeland**) use `make`; this is likely because `npm` is full of single-purpose modules. This is where `make` shines. In many cases, the complexity cost of Grunt is unnecessary.

That being said, Grunt is a nice tool; though it is much more complicated than `make`. Having good documentation helps though :+1: . To be fair, `make` has plenty of documentation, but it is a bit scattered (someone should fix this).

> Its [make] syntax is confusing to people who don't know it already

JavaScript syntax is no panacea either. Do you remember when `!!~` looked foreign? It's obvious now that you've been doing JS (or any other language that supports unary operations); however, there was a time when you had to pick up the documentation and level-up.

This is also the case with Grunt. Not all web developers are familiar with NodeJS so in many cases, it requires some reading. This is the case w/ `grunt` or `make` or anything else.

On the other hand, a casual user of a project shouldn't care either way. It only matters once you've decided to contribute and you need to run the unit tests and/or build a release. At that point, as a contributor, you've got to learn the tools that are out there and `make` has been out there for a long time. Being a _web_ developer doesn't relieve one of the responsibility of learning proven industry tools. This also means, no complaining when a project does indeed use `grunt` when it was the right tool for the job; because sometimes it is :)

> web developers do not use make

That's not true.

On the other hand...I'm sure that if someone felt strong enough for Grunt to put in a PR, there is little reason to not accept it. Like I mentioned above, it's a great tool but let's not throw `make` under the bus just for fun. :+1:  for speaking with code.

BTW, the [Makefile](https://github.com/mozilla/brick/blob/master/Makefile) for this project is like 35 loc (tiny) including the target names. I'd be interested to see the corresponding `Gruntfile`; I'd be surprised if the line count wasn't comparable or perhaps the `Gruntfile` may even be larger. That being said, I also notice that some of the underlying build tasks are really living under https://github.com/mozilla/brick/tree/master/build (JavaScript source). To get the equivalent in Grunt, you'd end up writing ~ the same amount of `JS` anyway -- though much of this could be factored into `grunt-*` node modules. Either is probably fine.

My observation has been that large applications (not libs) benefit from using Grunt. Although, to be fair, there are some huge frameworks that also benefit. Use the best tool for the job at hand.

Finally, it is entirely acceptable to use a `Makefile` and a `Gruntfile` for their strengths in the same project.

**Comment by fwenzel** [comment]
> On the other hand...I'm sure that if someone felt strong enough for Grunt to put in a PR, there is little reason to not accept it. Like I mentioned above, it's a great tool but let's not throw make under the bus just for fun. :+1: for speaking with code.

Truth! :+1:

**Comment by eriwen** [comment]
@wilmoore Well said!

**Comment by tj** [comment]
web developers don't use make, they re-invent make ;)

**Comment by mcepl** [comment]
There are many places in the world (like my computer ATM), where node doesn't work at all (because of its complex dependencies on V8 etc., which is currently broken again), whereas I cannot imagine a computer which couldn't have working make. Of course, decent any OS ships it as part of system, the other system has at least plenty of third party ports.

**Comment by sole** [comment]
OK closing since it seems no one wants to write a node script (including me) and make seems to work... for now :P

**Comment by pennyfx** [comment]
@sole funny, you closed it right when I started working on it...  reopening.

**Comment by sole** [comment]
Sorry! I just didn't want to distract you guys :)
Glad you started looking into it ^_^

**Comment by potch** [comment]
We are about to merge a move from `make` to `grunt`! Details forthcoming.

**Comment by potch** [comment]
hah, this is so done.
