### ISSUE TITLE
Create Brick Action Menu

### ISSUE THREAD

**Issue by rorito** [mozbrick/brick#207]
Gaia 2.0 PSD 
https://www.dropbox.com/sh/klpt0h6pfe2rjn7/AADUs0J_XEsQEsOPH9qlyvZwa

Gaia 2.0 CSS examples (by Casey & Wilson)
https://github.com/caseyyee/gaia-controls
http://caseyyee.github.io/gaia-controls/src/app/index.html

Existing Gaia 1.3 Action Menu
http://buildingfirefoxos.com/building-blocks/action-menu.html

**Comment by lmorchard** [comment]
I can try taking a crack at this

**Comment by fwenzel** [comment]
@dotch can help answer questions if you have any :)

**Comment by dotch** [comment]
yes. our yeoman generator is a good starting point. https://github.com/mozbrick/generator-brick

**Comment by lmorchard** [comment]
Dumped some in-progress work onto github:

https://github.com/lmorchard/brick-action-menu
http://lmorchard.github.io/brick-action-menu/

**Comment by lmorchard** [comment]
Okay, I think I have a first rough feature complete version based on CSS stolen from buildingfirefoxos.

Haven't yet taken a look at theme support, or at using the newer guidelines. I plan to do that next.

But, this could probably use some eyeballs on it now if only to tell me if I'm entirely off base with how these things need to be built. (and also because I'm rusty on the client-side and could use some brutal critique)

**Comment by dotch** [comment]
I can take a look at it!
if you want to catch up on how we do theme support and our slightly different new build process take a look at [brick-tabbar](https://github.com/mozbrick/brick-tabbar).

**Comment by lmorchard** [comment]
Cool beans, I'll take a swing by brick-tabbar and see what I can port over to here!

**Comment by fwenzel** [comment]
How does the buildingfirefoxos style relate to Gaia 2.0? We might not get away with stealing CSS only from there :-/

**Comment by dotch** [comment]
maybe dialogues (especially action dialogue) form [caseyyee](http://caseyyee.github.io/gaia-controls/) are a better way to style this?

**Comment by lmorchard** [comment]
Yes, [like I said](https://github.com/mozbrick/brick/issues/207#issuecomment-50801156), using the gaia 2.0 styling is where I'm going next. The buildingfirefoxos style is just what I got pointed to first, using it temporarily as I work out the rest.

Mainly asking for some feedback here on the web components basics, as well as the little bit of API this tag exposes.

**Comment by lmorchard** [comment]
Okay, still working on it. But, I have some baby steps toward some copypasta of caseyyee's styles. Again, though, what I really need is feedback on the JS & web components bits behind the scenes

**Comment by dotch** [comment]
Sorry for not reviewing your code earlier.
I looked at it and did not find any issues with the js and webcomponent stuff. It is so far perfectly in line with what we do in the other components.
The only possible css thing i can recommend is using `host([visible])` instead of `host[visible]` even though both work, bu the first seems to be the [right way to do it](http://dev.w3.org/csswg/css-scoping/#selectordef-host)

**Comment by lmorchard** [comment]
Cool, thanks for the look! I'll poke at the CSS some more. Still wrapping my head around stylus a bit and what to separate from the core style into the theme. Assuming most of the gaia 2.0 stuff should go there

FWIW, you probably missed most of the dumb stuff I did and then stripped out after getting a closer look at tabbar :)

**Comment by lmorchard** [comment]
Not sure where else to go with this thing after tinkering today. Got pretty much all of the Gaia 2.0 CSS working, along with some transitions. Not loading the gaia fonts on my demo page, so it looks a little different.

I guess now my questions are: Is it done enough? And if so, what do I do next to make it "official"?

**Comment by lmorchard** [comment]
FWIW, I just transferred ownership of my repo to [mozbrick/brick-action-menu](https://github.com/mozbrick/brick-action-menu). So, I'm going to call this issue done, because the component was _created_. Go ahead and plaster the thing with issues over at that repo.
