### ISSUE TITLE
Add Date Range selection to x-calendar

### ISSUE THREAD

**Issue by dlindenkreuz** [mozbrick/brick#40]
I highly recommend adding proper date range selection to the x-calendar component as selecting multiple dates one by one is not what users expect. Every calendar "widget" should provide this feature (and I guess most of the good ones do).

**Comment by ldoubleuz** [comment]
If you want to be able to just pick a start and end date for a range instead of selecting the dates themselves, you can simulate this for the moment by utilizing two &lt;x-datepicker&gt;s, similar to how [jQuery UI does it](http://jqueryui.com/datepicker/#date-range). 

However, date range selection would be a good feature, so adding a feature to restrict the available dates on an x-calendar would allow the UI for x-datepickers to be more intuitive, and is something we'll keep in mind.

**Comment by p0ffsrule** [comment]
Is it ok if I tried working on this?

**Comment by sole** [comment]
While we wait for @potch or @pennyfx to confirm it's OK to take this bug, I'd say go ahead if this is an issue that interests you, and let us know how it works for you--any issues or stumbling blocks you find, etc.

Thanks for contributing! :smile:

**Comment by p0ffsrule** [comment]
I'd just need to know a few details about how exactly you'd need it implemented.  Like the UI and so on.

**Comment by sole** [comment]
This is something someone suggested... What about sketching some ideas and discussing them before coding anything? :)

**Comment by p0ffsrule** [comment]
Right.  I thought it could be added to the 'multiple' attribute and have a little button to add a range selection mode where the next 2 dates selected would define the range.  Only thing is that there wouldn't be any space in the layout for such a button.

**Comment by p0ffsrule** [comment]
Or would it be better if I created a new attribute 'range'?  Seems like overkill...

**Comment by sole** [comment]
So these are the current attributes:
http://mozilla.github.io/brick/docs.html#x-tag-calendar

`multiple` allows for multiple dates to be selected and `chosen` holds the dates themselves.

I was thinking that one way of approaching this could be to have a `allowRanges` attribute (or just `ranges`?) that when present allows you to "point and drag" several dates (starting from the first one you selected). Internally we would simply update the `chosen` data according to whatever was in the range.

**Comment by p0ffsrule** [comment]
But the point and drag wouldn't be very convenient if the range spanned more than 1 month.

**Comment by sole** [comment]
Yeah I thought that for a moment, too. But we want the point and drag to quickly select dates rather than clicking on each of the potentially 31 days in the month, right? This would be a solution to that issue: if `allowRanges` is enabled, holding down and moving the finger or clicking down and dragging should select multiple dates.

I think the "spanned more than 1 month" is another problem :-)

**Comment by p0ffsrule** [comment]
OK.  I'll try it like that.

**Comment by dotch** [comment]
closing because it will tracked in the individual repo at https://github.com/mozbrick/brick-calendar/issues/3
