### ISSUE TITLE
[Website] Brick in Action is not working

### ISSUE THREAD

**Issue by jaydson** [mozbrick/brick#85]
The toggle flip example http://mozilla.github.io/brick/index.html is not working properly.

**Comment by pennyfx** [comment]
I just confirmed that flipbox on the demo page works.

**Comment by nadrimajstor** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) http://mozilla.github.io/brick/component/flipbox/demo/demo.css
Failed to load resource: the server responded with a status of 404 (Not Found) http://mozilla.github.io/brick/component/flipbox/demo/demo.js

Shouldn't path be: `/brick/demos/flipbox/demo.js` instead of `/brick/component/flipbox/demo/demo.js` ?

**Comment by potch** [comment]
@jaydson are you still encountering this?

**Comment by jaydson** [comment]
Nope, now it's working pretty well.

**Comment by fwenzel** [comment]
We're glad. Thanks for filing!
