### ISSUE TITLE
x-calendar do not work properly

### ISSUE THREAD

**Issue by bourduard** [mozbrick/brick#96]
While go through months it jumps from january to march (skip february)

**Comment by pennyfx** [comment]
I had this issue on a calendar control I created a while back.  I'll take a look.

**Comment by pennyfx** [comment]
We are working on a fix.  Not sure if it will be finished today (10/31/2013).  It happens because the number of days in this month are greater than a month you iterate to in the calendar.   This issue will go away tomorrow (11/1/2013), but will raise it's nasty head every time todays date is greater than another month in the calendar.      Fix is coming soon.

https://github.com/mozilla/brick/issues/99
https://github.com/mozilla/brick/issues/100

**Comment by potch** [comment]
Apologies about the brokenness! I'm rolling out a new version with a fix today.

**Comment by pennyfx** [comment]
Here's the fix.  https://github.com/x-tag/calendar/commit/1e87e1276af98970f7e9183bc9508f5323280428
@potch has the website been updated?

**Comment by pennyfx** [comment]
Brick is updated with latest changes.
